./compile.sh ./StaticMembersSol
./compile.sh ./MusicStoreSol
./compile.sh ./DangerousCastingSol
./compile.sh ./EvolutionRedesign3Ex
./compile.sh ./PrimeNumbersSol
./compile.sh ./RTTIAndMetaEx
./compile.sh ./EvolutionRedesign4Sol
./compile.sh ./RecursiveCompositeSol
./compile.sh ./IdiomsEx
./compile.sh ./PersonConstructorEx
./compile.sh ./WordGeneratorSol
./compile.sh ./FriendEx
./compile.sh ./EvolutionRedesign4Ex
./compile.sh ./FriendSol
./compile.sh ./RecursiveCompositeEx
./compile.sh ./FactorySol
./compile.sh ./lib/test
./compile.sh ./ContractsSol
./compile.sh ./CommonInterfaceEx
./compile.sh ./AddressBookSol
./compile.sh ./WordGeneratorEx
./compile.sh ./SafeCastingSol
./compile.sh ./Namespaces2Sol
./compile.sh ./EvolutionOfCProgOriginalEx
./compile.sh ./StringTestsEx
./compile.sh ./StaticMembersEx
./compile.sh ./pass_byEx
./compile.sh ./CopyCtorAssignmentOpEx
./compile.sh ./ExceptionsSol
./compile.sh ./ReferencePointerValueSol
./compile.sh ./RTTISol
./compile.sh ./WordsSetSol
./compile.sh ./interfacesSol
./compile.sh ./InlineFunctionsSol
./compile.sh ./stltestSol
./compile.sh ./inheritanceSol
./compile.sh ./IdiomsSol
./compile.sh ./CardDeckEx
./compile.sh ./SmartPointerEx
./compile.sh ./PersonDestructorEx
./compile.sh ./virtual_functionEx
./compile.sh ./DefaultParametersEx
./compile.sh ./ExceptionsEx
./compile.sh ./CommonInterfaceSol
./compile.sh ./RTTIEx
./compile.sh ./stl1Ex
./compile.sh ./CallbackSol
./compile.sh ./VirtualDestructorsSol
./compile.sh ./CardDeckSol
./compile.sh ./PersonDestructorSol
./compile.sh ./interfacesEx
./compile.sh ./AllocatorSol
./compile.sh ./ObserverEx
./compile.sh ./SimpleContainerTestEx
./compile.sh ./EvolutionRedesign1Ex
./compile.sh ./ReferencePointerValueEx
./compile.sh ./RTTIAndMetaSol
./compile.sh ./InlineFunctionsEx
./compile.sh ./stl2Ex
./compile.sh ./EvolutionRedesign2Ex
./compile.sh ./ObserverSol
./compile.sh ./virtual_functionSol
./compile.sh ./StripperSol
./compile.sh ./inlineSol
./compile.sh ./StripperEx
./compile.sh ./CardSol
./compile.sh ./SafeCastingEx
./compile.sh ./EliminatingCastingSol
./compile.sh ./ShapeImplementationSol
./compile.sh ./TemplateSol
./compile.sh ./ShapeMetaEx
./compile.sh ./OperatorOverloadingEx
./compile.sh ./inheritanceEx
./compile.sh ./NamespacesEx
./compile.sh ./SmartPointerSol
./compile.sh ./SequenceContainersEx
./compile.sh ./DefaultParametersSol
./compile.sh ./TemplateEx
./compile.sh ./ConstEx
./compile.sh ./ContractsEx
./compile.sh ./ConstSol
./compile.sh ./DangerousCastingEx
./compile.sh ./GenericCallbackSol
./compile.sh ./AddressBookEx
./compile.sh ./PrimeNumbersEx
./compile.sh ./TemplateMethodSol
./compile.sh ./AlgorithmTestEx
./compile.sh ./OperatorOverloadingSol
./compile.sh ./MusicStoreEx
./compile.sh ./WordsWithAlgorithmsSol
./compile.sh ./CardEx
./compile.sh ./OtherContainerTestEx
./compile.sh ./VirtualDestructorsEx
./compile.sh ./Namespaces1Sol
./compile.sh ./AssociativeContainerTestEx
./compile.sh ./CopyCtorAssignmentOpSol
./compile.sh ./PersonConstructorSol
./compile.sh ./FactoryEx
./compile.sh ./inlineEx
./compile.sh ./EliminatingCastingEx
./compile.sh ./pass_bySol
./compile.sh ./ShapeImplementationEx
./compile.sh ./CounterAppEx
./compile.sh ./WordsDequeSol
./compile.sh ./TemplateMethodEx
./compile.sh ./ShapeMetaSol
./compile.sh ./GenericCallbackEx
./compile.sh ./CallbackEx
